#!/bin/sh /etc/rc.common

START=999

start() {
        test -f /etc/crontabs/root || touch /etc/crontabs/root

        HOUR=$(expr $(head /dev/urandom | tr -dc "0123456789" | head -c3) % 24)
        MINUTE=$(expr $(head /dev/urandom | tr -dc "0123456789" | head -c3) % 60)

        grep -q hlos-update /etc/crontabs/root || {
                echo $MINUTE $HOUR '* * * (hlos-update 2>&1 | logger -t hlos-update -s)' >> /etc/crontabs/root
		/etc/init.d/cron restart
        }
}

